spark_local:
  target: dev
  outputs:
    dev:
      type: spark
      method: session
      catalog: local
      schema: db
      host: NA
      server_side_parameters:
        "spark.driver.memory": "4g"
        "spark.jars.packages": "org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.9.1"
        "spark.sql.extensions": "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions"
        "spark.sql.extensions": "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions"
        "spark.sql.catalog.local": "org.apache.iceberg.spark.SparkCatalog"
        "spark.sql.catalog.local.type": "hive"
        "spark.sql.catalog.local.warehouse": "/usr/hive/warehouse"
        "spark.sql.catalog.local.uri": "thrift://localhost:9083"
        "spark.sql.defaultCatalog": "local"