spark_local:
  target: dev
  outputs:
    dev:
      type: spark
      method: session
      schema: staging
      host: localhost
      port: 10000
      database: staging
      threads: 1
      use_ssl: false