CREATE DATABASE IF NOT EXISTS db;
USE db;

-- Nation
CREATE OR REPLACE TABLE nation (
  N_NATIONKEY  INTEGER NOT NULL,
  N_NAME       STRING NOT NULL,
  N_REGIONKEY  INTEGER NOT NULL,
  N_COMMENT    STRING,
  N_LOADTIMESTAMP TIMESTAMP 
)
USING iceberg;

INSERT INTO nation
SELECT CAST(_c0 AS INT), _c1, CAST(_c2 AS INT), _c3, current_timestamp()
FROM csv.`/mnt/project/seeds/nation.csv`;

-- Region
CREATE OR REPLACE TABLE region (
  R_REGIONKEY  INTEGER NOT NULL,
  R_NAME       STRING NOT NULL,
  R_COMMENT    STRING,
  R_LOADTIMESTAMP TIMESTAMP 
)
USING iceberg;

INSERT INTO region
SELECT CAST(_c0 AS INT), _c1, _c2, current_timestamp()
FROM csv.`/mnt/project/seeds/region.csv`;

-- Part
CREATE OR REPLACE TABLE part (
  P_PARTKEY     INTEGER NOT NULL,
  P_NAME        STRING NOT NULL,
  P_MFGR        STRING NOT NULL,
  P_BRAND       STRING NOT NULL,
  P_TYPE        STRING NOT NULL,
  P_SIZE        INTEGER NOT NULL,
  P_CONTAINER   STRING NOT NULL,
  P_RETAILPRICE DECIMAL(15,2) NOT NULL,
  P_COMMENT     STRING,
  P_LOADTIMESTAMP TIMESTAMP 
)
USING iceberg;

INSERT INTO part
SELECT CAST(_c0 AS INT), _c1, _c2, _c3, _c4, CAST(_c5 AS INT), _c6, CAST(_c7 AS DECIMAL(15,2)), _c8, current_timestamp()
FROM csv.`/mnt/project/seeds/part.csv`;

-- Supplier
CREATE OR REPLACE TABLE supplier (
  S_SUPPKEY     INTEGER NOT NULL,
  S_NAME        STRING NOT NULL,
  S_ADDRESS     STRING NOT NULL,
  S_NATIONKEY   INTEGER NOT NULL,
  S_PHONE       STRING NOT NULL,
  S_ACCTBAL     DECIMAL(15,2) NOT NULL,
  S_COMMENT     STRING,
  S_LOADTIMESTAMP TIMESTAMP 
)
USING iceberg;

INSERT INTO supplier
SELECT CAST(_c0 AS INT), _c1, _c2, CAST(_c3 AS INT), _c4, CAST(_c5 AS DECIMAL(15,2)), _c6, current_timestamp()
FROM csv.`/mnt/project/seeds/supplier.csv`;

-- Partsupp
CREATE OR REPLACE TABLE partsupp (
  PS_PARTKEY     INTEGER NOT NULL,
  PS_SUPPKEY     INTEGER NOT NULL,
  PS_AVAILQTY    INTEGER NOT NULL,
  PS_SUPPLYCOST  DECIMAL(15,2) NOT NULL,
  PS_COMMENT     STRING,
  PS_LOADTIMESTAMP TIMESTAMP 
)
USING iceberg;

INSERT INTO partsupp
SELECT CAST(_c0 AS INT), CAST(_c1 AS INT), CAST(_c2 AS INT), CAST(_c3 AS DECIMAL(15,2)), _c4, current_timestamp()
FROM csv.`/mnt/project/seeds/partsupp.csv`;

-- Customer
CREATE OR REPLACE TABLE customer (
  C_CUSTKEY     INTEGER NOT NULL,
  C_NAME        STRING NOT NULL,
  C_ADDRESS     STRING NOT NULL,
  C_NATIONKEY   INTEGER NOT NULL,
  C_PHONE       STRING NOT NULL,
  C_ACCTBAL     DECIMAL(15,2) NOT NULL,
  C_MKTSEGMENT  STRING NOT NULL,
  C_COMMENT     STRING,
  C_LOADTIMESTAMP TIMESTAMP 
)
USING iceberg;

INSERT INTO customer
SELECT CAST(_c0 AS INT), _c1, _c2, CAST(_c3 AS INT), _c4, CAST(_c5 AS DECIMAL(15,2)), _c6, _c7, current_timestamp()
FROM csv.`/mnt/project/seeds/customer.csv`;

-- Orders
CREATE OR REPLACE TABLE orders (
  O_ORDERKEY       INTEGER NOT NULL,
  O_CUSTKEY        INTEGER NOT NULL,
  O_ORDERSTATUS    STRING NOT NULL,
  O_TOTALPRICE     DECIMAL(15,2) NOT NULL,
  O_ORDERDATE      DATE NOT NULL,
  O_ORDERPRIORITY  STRING NOT NULL,
  O_CLERK          STRING NOT NULL,
  O_SHIPPRIORITY   INTEGER NOT NULL,
  O_COMMENT        STRING,
  O_LOADTIMESTAMP TIMESTAMP 
)
USING iceberg;

INSERT INTO orders
SELECT CAST(_c0 AS INT), CAST(_c1 AS INT), _c2, CAST(_c3 AS DECIMAL(15,2)), CAST(_c4 AS DATE), _c5, _c6, CAST(_c7 AS INT), _c8, current_timestamp()
FROM csv.`/mnt/project/seeds/orders.csv`;

-- Lineitem
CREATE OR REPLACE TABLE lineitem (
  L_ORDERKEY      INTEGER NOT NULL,
  L_PARTKEY       INTEGER NOT NULL,
  L_SUPPKEY       INTEGER NOT NULL,
  L_LINENUMBER    INTEGER NOT NULL,
  L_QUANTITY      DECIMAL(15,2) NOT NULL,
  L_EXTENDEDPRICE DECIMAL(15,2) NOT NULL,
  L_DISCOUNT      DECIMAL(15,2) NOT NULL,
  L_TAX           DECIMAL(15,2) NOT NULL,
  L_RETURNFLAG    STRING NOT NULL,
  L_LINESTATUS    STRING NOT NULL,
  L_SHIPDATE      DATE NOT NULL,
  L_COMMITDATE    DATE NOT NULL,
  L_RECEIPTDATE   DATE NOT NULL,
  L_SHIPINSTRUCT  STRING NOT NULL,
  L_SHIPMODE      STRING NOT NULL,
  L_COMMENT       STRING,
  L_LOADTIMESTAMP TIMESTAMP 
)
USING iceberg;

INSERT INTO lineitem
SELECT CAST(_c0 AS INT), CAST(_c1 AS INT), CAST(_c2 AS INT), CAST(_c3 AS INT),
       CAST(_c4 AS DECIMAL(15,2)), CAST(_c5 AS DECIMAL(15,2)), CAST(_c6 AS DECIMAL(15,2)),
       CAST(_c7 AS DECIMAL(15,2)), _c8, _c9,
       CAST(_c10 AS DATE), CAST(_c11 AS DATE), CAST(_c12 AS DATE),
       _c13, _c14, _c15, current_timestamp()
FROM csv.`/mnt/project/seeds/lineitem.csv`;
