version: '3.8'

services:
  spark:
    build: .
    container_name: spark-iceberg
    volumes:
      - "${PROJECT_DIRECTORY_PATH}:/mnt/project"
      - "${WAREHOUSE_DIRECTORY_PATH}:/usr/hive/warehouse"
    stdin_open: true
    tty: true