version: '3.8'

services:
  spark:
    build: .
    container_name: spark-iceberg
    volumes:
      - "../:/mnt/project"
    environment:
      - SPARK_CONF_DIR=/opt/bitnami/spark/conf
    stdin_open: true
    tty: true